name: Package Addon

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*.lua"
      - "WowNote.toc"
      - ".github/workflows/package.yml"
      - "scripts/package.sh"

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create addon ZIP
        run: |
          mkdir -p build/WowNote

          cp WowNote.toc build/WowNote/
          cp *.lua build/WowNote/

          cd build
          zip -r WowNote.zip WowNote

      - name: Upload addon ZIP
        uses: actions/upload-artifact@v4
        with:
          name: WowNote-installable
          path: build/WowNote.zip
          if-no-files-found: error